THEMES = {
    "opencode": {
        "bg":           "#0d0d0d",
        "bg_panel":     "#111111",
        "bg_element":   "#1a1a1a",
        "border":       "#2a2a2a",
        "border_active":"#444444",
        "text":         "#e0e0e0",
        "text_muted":   "#666666",
        "primary":      "#fab283",
        "secondary":    "#5c9cf5",
        "accent":       "#9d7cd8",
        "success":      "#7fd88f",
        "error":        "#e06c75",
        "warning":      "#f5a742",
        "syntax_kw":    "#9d7cd8",
        "syntax_fn":    "#fab283",
        "syntax_str":   "#7fd88f",
        "syntax_num":   "#5c9cf5",
        "syntax_cmt":   "#555555",
        "syntax_type":  "#5c9cf5",
    },
    "tokyonight": {
        "bg":           "#1a1b26",
        "bg_panel":     "#16161e",
        "bg_element":   "#1f2335",
        "border":       "#292e42",
        "border_active":"#3d59a1",
        "text":         "#c0caf5",
        "text_muted":   "#565f89",
        "primary":      "#7aa2f7",
        "secondary":    "#bb9af7",
        "accent":       "#7dcfff",
        "success":      "#9ece6a",
        "error":        "#f7768e",
        "warning":      "#e0af68",
        "syntax_kw":    "#bb9af7",
        "syntax_fn":    "#7aa2f7",
        "syntax_str":   "#9ece6a",
        "syntax_num":   "#ff9e64",
        "syntax_cmt":   "#565f89",
        "syntax_type":  "#7dcfff",
    },
    "everforest": {
        "bg":           "#2d353b",
        "bg_panel":     "#272e33",
        "bg_element":   "#343f44",
        "border":       "#3d484d",
        "border_active":"#7a8478",
        "text":         "#d3c6aa",
        "text_muted":   "#7a8478",
        "primary":      "#a7c080",
        "secondary":    "#7fbbb3",
        "accent":       "#83c092",
        "success":      "#a7c080",
        "error":        "#e67e80",
        "warning":      "#dbbc7f",
        "syntax_kw":    "#e69875",
        "syntax_fn":    "#a7c080",
        "syntax_str":   "#83c092",
        "syntax_num":   "#d699b6",
        "syntax_cmt":   "#7a8478",
        "syntax_type":  "#7fbbb3",
    },
    "ayu": {
        "bg":           "#0d1017",
        "bg_panel":     "#0f1420",
        "bg_element":   "#131721",
        "border":       "#1e2430",
        "border_active":"#e6b450",
        "text":         "#bfbdb6",
        "text_muted":   "#3d4a5c",
        "primary":      "#e6b450",
        "secondary":    "#39bae6",
        "accent":       "#59c2ff",
        "success":      "#aad94c",
        "error":        "#f26d78",
        "warning":      "#ffb454",
        "syntax_kw":    "#ff8f40",
        "syntax_fn":    "#ffb454",
        "syntax_str":   "#aad94c",
        "syntax_num":   "#e6b450",
        "syntax_cmt":   "#3d4a5c",
        "syntax_type":  "#39bae6",
    },
    "catppuccin": {
        "bg":           "#1e1e2e",
        "bg_panel":     "#181825",
        "bg_element":   "#313244",
        "border":       "#45475a",
        "border_active":"#cba6f7",
        "text":         "#cdd6f4",
        "text_muted":   "#6c7086",
        "primary":      "#cba6f7",
        "secondary":    "#89b4fa",
        "accent":       "#f5c2e7",
        "success":      "#a6e3a1",
        "error":        "#f38ba8",
        "warning":      "#fab387",
        "syntax_kw":    "#cba6f7",
        "syntax_fn":    "#89b4fa",
        "syntax_str":   "#a6e3a1",
        "syntax_num":   "#fab387",
        "syntax_cmt":   "#6c7086",
        "syntax_type":  "#89dceb",
    },
    "catppuccin-macchiato": {
        "bg":           "#24273a",
        "bg_panel":     "#1e2030",
        "bg_element":   "#363a4f",
        "border":       "#494d64",
        "border_active":"#c6a0f6",
        "text":         "#cad3f5",
        "text_muted":   "#6e738d",
        "primary":      "#c6a0f6",
        "secondary":    "#8aadf4",
        "accent":       "#f5bde6",
        "success":      "#a6da95",
        "error":        "#ed8796",
        "warning":      "#f5a97f",
        "syntax_kw":    "#c6a0f6",
        "syntax_fn":    "#8aadf4",
        "syntax_str":   "#a6da95",
        "syntax_num":   "#f5a97f",
        "syntax_cmt":   "#6e738d",
        "syntax_type":  "#91d7e3",
    },
    "gruvbox": {
        "bg":           "#282828",
        "bg_panel":     "#1d2021",
        "bg_element":   "#3c3836",
        "border":       "#504945",
        "border_active":"#d79921",
        "text":         "#ebdbb2",
        "text_muted":   "#928374",
        "primary":      "#d79921",
        "secondary":    "#458588",
        "accent":       "#b16286",
        "success":      "#98971a",
        "error":        "#cc241d",
        "warning":      "#d65d0e",
        "syntax_kw":    "#fb4934",
        "syntax_fn":    "#fabd2f",
        "syntax_str":   "#b8bb26",
        "syntax_num":   "#d3869b",
        "syntax_cmt":   "#928374",
        "syntax_type":  "#83a598",
    },
    "kanagawa": {
        "bg":           "#1f1f28",
        "bg_panel":     "#16161d",
        "bg_element":   "#2a2a37",
        "border":       "#363646",
        "border_active":"#7e9cd8",
        "text":         "#dcd7ba",
        "text_muted":   "#727169",
        "primary":      "#7e9cd8",
        "secondary":    "#957fb8",
        "accent":       "#6a9589",
        "success":      "#76946a",
        "error":        "#c34043",
        "warning":      "#ff9e3b",
        "syntax_kw":    "#957fb8",
        "syntax_fn":    "#7e9cd8",
        "syntax_str":   "#98bb6c",
        "syntax_num":   "#d27e99",
        "syntax_cmt":   "#727169",
        "syntax_type":  "#7aa89f",
    },
    "nord": {
        "bg":           "#2e3440",
        "bg_panel":     "#242933",
        "bg_element":   "#3b4252",
        "border":       "#434c5e",
        "border_active":"#88c0d0",
        "text":         "#d8dee9",
        "text_muted":   "#4c566a",
        "primary":      "#88c0d0",
        "secondary":    "#81a1c1",
        "accent":       "#8fbcbb",
        "success":      "#a3be8c",
        "error":        "#bf616a",
        "warning":      "#ebcb8b",
        "syntax_kw":    "#81a1c1",
        "syntax_fn":    "#88c0d0",
        "syntax_str":   "#a3be8c",
        "syntax_num":   "#b48ead",
        "syntax_cmt":   "#4c566a",
        "syntax_type":  "#8fbcbb",
    },
    "matrix": {
        "bg":           "#000000",
        "bg_panel":     "#020f02",
        "bg_element":   "#041404",
        "border":       "#0a3a0a",
        "border_active":"#00ff00",
        "text":         "#00cc00",
        "text_muted":   "#005500",
        "primary":      "#00ff00",
        "secondary":    "#00aa00",
        "accent":       "#33ff33",
        "success":      "#00ff00",
        "error":        "#ff0000",
        "warning":      "#ffff00",
        "syntax_kw":    "#00ff00",
        "syntax_fn":    "#33ff33",
        "syntax_str":   "#009900",
        "syntax_num":   "#00cc00",
        "syntax_cmt":   "#005500",
        "syntax_type":  "#00ff88",
    },
    "one-dark": {
        "bg":           "#282c34",
        "bg_panel":     "#21252b",
        "bg_element":   "#2c313a",
        "border":       "#3e4451",
        "border_active":"#61afef",
        "text":         "#abb2bf",
        "text_muted":   "#5c6370",
        "primary":      "#61afef",
        "secondary":    "#c678dd",
        "accent":       "#56b6c2",
        "success":      "#98c379",
        "error":        "#e06c75",
        "warning":      "#e5c07b",
        "syntax_kw":    "#c678dd",
        "syntax_fn":    "#61afef",
        "syntax_str":   "#98c379",
        "syntax_num":   "#d19a66",
        "syntax_cmt":   "#5c6370",
        "syntax_type":  "#56b6c2",
    },
}

THEME_DESCRIPTIONS = {
    "opencode":             "OpenCode's default dark theme",
    "tokyonight":           "Deep blue/purple nights",
    "everforest":           "Warm green forest tones",
    "ayu":                  "Orange & teal on deep dark",
    "catppuccin":           "Soft pastel dark",
    "catppuccin-macchiato": "Darker catppuccin variant",
    "gruvbox":              "Retro warm brown & yellow",
    "kanagawa":             "Japanese ink-inspired blues",
    "nord":                 "Arctic cold blue-grey",
    "matrix":               "Hacker green on black",
    "one-dark":             "Atom One Dark",
}
