THEMES = {
    "system": {
        "bg":           "#0d1117",
        "bg_panel":     "#161b22",
        "bg_element":   "#21262d",
        "border":       "#30363d",
        "border_active":"#58a6ff",
        "text":         "#c9d1d9",
        "text_muted":   "#8b949e",
        "primary":      "#58a6ff",
        "secondary":    "#3fb950",
        "accent":       "#bc8cff",
        "success":      "#3fb950",
        "error":        "#f85149",
        "warning":      "#d29922",
        "syntax_kw":    "#bc8cff",
        "syntax_fn":    "#58a6ff",
        "syntax_str":   "#3fb950",
        "syntax_num":   "#d29922",
        "syntax_cmt":   "#8b949e",
        "syntax_type":  "#76e3ea",
    },
    "ayu": {
        "bg":           "#0d1017",
        "bg_panel":     "#0f1420",
        "bg_element":   "#131721",
        "border":       "#1e2430",
        "border_active":"#e6b450",
        "text":         "#bfbdb6",
        "text_muted":   "#3d4a5c",
        "primary":      "#e6b450",
        "secondary":    "#39bae6",
        "accent":       "#59c2ff",
        "success":      "#aad94c",
        "error":        "#f26d78",
        "warning":      "#ffb454",
        "syntax_kw":    "#ff8f40",
        "syntax_fn":    "#ffb454",
        "syntax_str":   "#aad94c",
        "syntax_num":   "#e6b450",
        "syntax_cmt":   "#3d4a5c",
        "syntax_type":  "#39bae6",
    },
    "catppuccin": {
        "bg":           "#1e1e2e",
        "bg_panel":     "#181825",
        "bg_element":   "#313244",
        "border":       "#45475a",
        "border_active":"#cba6f7",
        "text":         "#cdd6f4",
        "text_muted":   "#6c7086",
        "primary":      "#cba6f7",
        "secondary":    "#89b4fa",
        "accent":       "#f5c2e7",
        "success":      "#a6e3a1",
        "error":        "#f38ba8",
        "warning":      "#fab387",
        "syntax_kw":    "#cba6f7",
        "syntax_fn":    "#89b4fa",
        "syntax_str":   "#a6e3a1",
        "syntax_num":   "#fab387",
        "syntax_cmt":   "#6c7086",
        "syntax_type":  "#89dceb",
    },
    "catppuccin-latte": {
        "bg":           "#eff1f5",
        "bg_panel":     "#bcc0cc",
        "bg_element":   "#acb0be",
        "border":       "#bcc0cc",
        "border_active":"#1e66f5",
        "text":         "#4c4f69",
        "text_muted":   "#acb0be",
        "primary":      "#1e66f5",
        "secondary":    "#1e66f5",
        "accent":       "#ea76cb",
        "success":      "#40a02b",
        "error":        "#d20f39",
        "warning":      "#df8e1d",
        "syntax_kw":    "#ea76cb",
        "syntax_fn":    "#1e66f5",
        "syntax_str":   "#40a02b",
        "syntax_num":   "#df8e1d",
        "syntax_cmt":   "#acb0be",
        "syntax_type":  "#179299",
    },
    "catppuccin-macchiato": {
        "bg":           "#24273a",
        "bg_panel":     "#1e2030",
        "bg_element":   "#363a4f",
        "border":       "#494d64",
        "border_active":"#c6a0f6",
        "text":         "#cad3f5",
        "text_muted":   "#6e738d",
        "primary":      "#c6a0f6",
        "secondary":    "#8aadf4",
        "accent":       "#f5bde6",
        "success":      "#a6da95",
        "error":        "#ed8796",
        "warning":      "#f5a97f",
        "syntax_kw":    "#c6a0f6",
        "syntax_fn":    "#8aadf4",
        "syntax_str":   "#a6da95",
        "syntax_num":   "#f5a97f",
        "syntax_cmt":   "#6e738d",
        "syntax_type":  "#91d7e3",
    },
    "ethereal": {
        "bg":           "#060B1E",
        "bg_panel":     "#3C486D",
        "bg_element":   "#6d7db6",
        "border":       "#3C486D",
        "border_active":"#7d82d9",
        "text":         "#ffcead",
        "text_muted":   "#6d7db6",
        "primary":      "#7d82d9",
        "secondary":    "#7d82d9",
        "accent":       "#c89dc1",
        "success":      "#92a593",
        "error":        "#ED5B5A",
        "warning":      "#E9BB4F",
        "syntax_kw":    "#c89dc1",
        "syntax_fn":    "#7d82d9",
        "syntax_str":   "#92a593",
        "syntax_num":   "#E9BB4F",
        "syntax_cmt":   "#6d7db6",
        "syntax_type":  "#a3bfd1",
    },
    "everforest": {
        "bg":           "#2d353b",
        "bg_panel":     "#272e33",
        "bg_element":   "#343f44",
        "border":       "#3d484d",
        "border_active":"#7a8478",
        "text":         "#d3c6aa",
        "text_muted":   "#7a8478",
        "primary":      "#a7c080",
        "secondary":    "#7fbbb3",
        "accent":       "#83c092",
        "success":      "#a7c080",
        "error":        "#e67e80",
        "warning":      "#dbbc7f",
        "syntax_kw":    "#e69875",
        "syntax_fn":    "#a7c080",
        "syntax_str":   "#83c092",
        "syntax_num":   "#d699b6",
        "syntax_cmt":   "#7a8478",
        "syntax_type":  "#7fbbb3",
    },
    "flexoki-light": {
        "bg":           "#FFFCF0",
        "bg_panel":     "#DAD8CE",
        "bg_element":   "#100F0F",
        "border":       "#DAD8CE",
        "border_active":"#205EA6",
        "text":         "#100F0F",
        "text_muted":   "#100F0F",
        "primary":      "#205EA6",
        "secondary":    "#205EA6",
        "accent":       "#CE5D97",
        "success":      "#879A39",
        "error":        "#D14D41",
        "warning":      "#D0A215",
        "syntax_kw":    "#CE5D97",
        "syntax_fn":    "#205EA6",
        "syntax_str":   "#879A39",
        "syntax_num":   "#D0A215",
        "syntax_cmt":   "#100F0F",
        "syntax_type":  "#3AA99F",
    },
    "gruvbox": {
        "bg":           "#282828",
        "bg_panel":     "#1d2021",
        "bg_element":   "#3c3836",
        "border":       "#504945",
        "border_active":"#d79921",
        "text":         "#ebdbb2",
        "text_muted":   "#928374",
        "primary":      "#d79921",
        "secondary":    "#458588",
        "accent":       "#b16286",
        "success":      "#98971a",
        "error":        "#cc241d",
        "warning":      "#d65d0e",
        "syntax_kw":    "#fb4934",
        "syntax_fn":    "#fabd2f",
        "syntax_str":   "#b8bb26",
        "syntax_num":   "#d3869b",
        "syntax_cmt":   "#928374",
        "syntax_type":  "#83a598",
    },
    "hackerman": {
        "bg":           "#0B0C16",
        "bg_panel":     "#3E4058",
        "bg_element":   "#6a6e95",
        "border":       "#3E4058",
        "border_active":"#82FB9C",
        "text":         "#ddf7ff",
        "text_muted":   "#6a6e95",
        "primary":      "#82FB9C",
        "secondary":    "#829dd4",
        "accent":       "#86a7df",
        "success":      "#4fe88f",
        "error":        "#50f872",
        "warning":      "#50f7d4",
        "syntax_kw":    "#86a7df",
        "syntax_fn":    "#829dd4",
        "syntax_str":   "#4fe88f",
        "syntax_num":   "#50f7d4",
        "syntax_cmt":   "#6a6e95",
        "syntax_type":  "#7cf8f7",
    },
    "kanagawa": {
        "bg":           "#1f1f28",
        "bg_panel":     "#16161d",
        "bg_element":   "#2a2a37",
        "border":       "#363646",
        "border_active":"#7e9cd8",
        "text":         "#dcd7ba",
        "text_muted":   "#727169",
        "primary":      "#7e9cd8",
        "secondary":    "#957fb8",
        "accent":       "#6a9589",
        "success":      "#76946a",
        "error":        "#c34043",
        "warning":      "#ff9e3b",
        "syntax_kw":    "#957fb8",
        "syntax_fn":    "#7e9cd8",
        "syntax_str":   "#98bb6c",
        "syntax_num":   "#d27e99",
        "syntax_cmt":   "#727169",
        "syntax_type":  "#7aa89f",
    },
    "lumon": {
        "bg":           "#16242d",
        "bg_panel":     "#1b2d40",
        "bg_element":   "#304860",
        "border":       "#1b2d40",
        "border_active":"#8bc9eb",
        "text":         "#d6e2ee",
        "text_muted":   "#304860",
        "primary":      "#8bc9eb",
        "secondary":    "#6fb8e3",
        "accent":       "#8bc9eb",
        "success":      "#5e95bc",
        "error":        "#4d86b0",
        "warning":      "#6fa4c9",
        "syntax_kw":    "#8bc9eb",
        "syntax_fn":    "#6fb8e3",
        "syntax_str":   "#5e95bc",
        "syntax_num":   "#6fa4c9",
        "syntax_cmt":   "#304860",
        "syntax_type":  "#b4e4f6",
    },
    "matrix": {
        "bg":           "#000000",
        "bg_panel":     "#020f02",
        "bg_element":   "#041404",
        "border":       "#0a3a0a",
        "border_active":"#00ff00",
        "text":         "#00cc00",
        "text_muted":   "#005500",
        "primary":      "#00ff00",
        "secondary":    "#00aa00",
        "accent":       "#33ff33",
        "success":      "#00ff00",
        "error":        "#ff0000",
        "warning":      "#ffff00",
        "syntax_kw":    "#00ff00",
        "syntax_fn":    "#33ff33",
        "syntax_str":   "#009900",
        "syntax_num":   "#00cc00",
        "syntax_cmt":   "#005500",
        "syntax_type":  "#00ff88",
    },
    "matte-black": {
        "bg":           "#000000",
        "bg_panel":     "#020f02",
        "bg_element":   "#041404",
        "border":       "#0a3a0a",
        "border_active":"#00ff00",
        "text":         "#00cc00",
        "text_muted":   "#005500",
        "primary":      "#00ff00",
        "secondary":    "#00aa00",
        "accent":       "#33ff33",
        "success":      "#00ff00",
        "error":        "#ff0000",
        "warning":      "#ffff00",
        "syntax_kw":    "#00ff00",
        "syntax_fn":    "#33ff33",
        "syntax_str":   "#009900",
        "syntax_num":   "#00cc00",
        "syntax_cmt":   "#005500",
        "syntax_type":  "#00ff88",
    },
    "miasma": {
        "bg":           "#222222",
        "bg_panel":     "#000000",
        "bg_element":   "#666666",
        "border":       "#000000",
        "border_active":"#78824b",
        "text":         "#c2c2b0",
        "text_muted":   "#666666",
        "primary":      "#78824b",
        "secondary":    "#78824b",
        "accent":       "#bb7744",
        "success":      "#5f875f",
        "error":        "#685742",
        "warning":      "#b36d43",
        "syntax_kw":    "#bb7744",
        "syntax_fn":    "#78824b",
        "syntax_str":   "#5f875f",
        "syntax_num":   "#b36d43",
        "syntax_cmt":   "#666666",
        "syntax_type":  "#c9a554",
    },
    "nord": {
        "bg":           "#2e3440",
        "bg_panel":     "#242933",
        "bg_element":   "#3b4252",
        "border":       "#434c5e",
        "border_active":"#88c0d0",
        "text":         "#d8dee9",
        "text_muted":   "#4c566a",
        "primary":      "#88c0d0",
        "secondary":    "#81a1c1",
        "accent":       "#8fbcbb",
        "success":      "#a3be8c",
        "error":        "#bf616a",
        "warning":      "#ebcb8b",
        "syntax_kw":    "#81a1c1",
        "syntax_fn":    "#88c0d0",
        "syntax_str":   "#a3be8c",
        "syntax_num":   "#b48ead",
        "syntax_cmt":   "#4c566a",
        "syntax_type":  "#8fbcbb",
    },
    "one-dark": {
        "bg":           "#282c34",
        "bg_panel":     "#21252b",
        "bg_element":   "#2c313a",
        "border":       "#3e4451",
        "border_active":"#61afef",
        "text":         "#abb2bf",
        "text_muted":   "#5c6370",
        "primary":      "#61afef",
        "secondary":    "#c678dd",
        "accent":       "#56b6c2",
        "success":      "#98c379",
        "error":        "#e06c75",
        "warning":      "#e5c07b",
        "syntax_kw":    "#c678dd",
        "syntax_fn":    "#61afef",
        "syntax_str":   "#98c379",
        "syntax_num":   "#d19a66",
        "syntax_cmt":   "#5c6370",
        "syntax_type":  "#56b6c2",
    },
    "opencode": {
        "bg":           "#0d0d0d",
        "bg_panel":     "#111111",
        "bg_element":   "#1a1a1a",
        "border":       "#2a2a2a",
        "border_active":"#444444",
        "text":         "#e0e0e0",
        "text_muted":   "#666666",
        "primary":      "#fab283",
        "secondary":    "#5c9cf5",
        "accent":       "#9d7cd8",
        "success":      "#7fd88f",
        "error":        "#e06c75",
        "warning":      "#f5a742",
        "syntax_kw":    "#9d7cd8",
        "syntax_fn":    "#fab283",
        "syntax_str":   "#7fd88f",
        "syntax_num":   "#5c9cf5",
        "syntax_cmt":   "#555555",
        "syntax_type":  "#5c9cf5",
    },
    "osaka-jade": {
        "bg":           "#111c18",
        "bg_panel":     "#23372B",
        "bg_element":   "#53685B",
        "border":       "#23372B",
        "border_active":"#509475",
        "text":         "#C1C497",
        "text_muted":   "#53685B",
        "primary":      "#509475",
        "secondary":    "#509475",
        "accent":       "#D2689C",
        "success":      "#549e6a",
        "error":        "#FF5345",
        "warning":      "#459451",
        "syntax_kw":    "#D2689C",
        "syntax_fn":    "#509475",
        "syntax_str":   "#549e6a",
        "syntax_num":   "#459451",
        "syntax_cmt":   "#53685B",
        "syntax_type":  "#2DD5B7",
    },
    "retro-82": {
        "bg":           "#05182e",
        "bg_panel":     "#303442",
        "bg_element":   "#134e5a",
        "border":       "#303442",
        "border_active":"#faa968",
        "text":         "#f6dcac",
        "text_muted":   "#134e5a",
        "primary":      "#faa968",
        "secondary":    "#faa968",
        "accent":       "#3f8f8a",
        "success":      "#028391",
        "error":        "#f85525",
        "warning":      "#e97b3c",
        "syntax_kw":    "#3f8f8a",
        "syntax_fn":    "#faa968",
        "syntax_str":   "#028391",
        "syntax_num":   "#e97b3c",
        "syntax_cmt":   "#134e5a",
        "syntax_type":  "#8cbfb8",
    },
    "ristretto": {
        "bg":           "#2c2525",
        "bg_panel":     "#72696a",
        "bg_element":   "#948a8b",
        "border":       "#72696a",
        "border_active":"#f38d70",
        "text":         "#e6d9db",
        "text_muted":   "#948a8b",
        "primary":      "#f38d70",
        "secondary":    "#f38d70",
        "accent":       "#a8a9eb",
        "success":      "#adda78",
        "error":        "#fd6883",
        "warning":      "#f9cc6c",
        "syntax_kw":    "#a8a9eb",
        "syntax_fn":    "#f38d70",
        "syntax_str":   "#adda78",
        "syntax_num":   "#f9cc6c",
        "syntax_cmt":   "#948a8b",
        "syntax_type":  "#85dacc",
    },
    "rose-pine": {
        "bg":           "#faf4ed",
        "bg_panel":     "#f2e9e1",
        "bg_element":   "#9893a5",
        "border":       "#f2e9e1",
        "border_active":"#56949f",
        "text":         "#575279",
        "text_muted":   "#9893a5",
        "primary":      "#56949f",
        "secondary":    "#56949f",
        "accent":       "#907aa9",
        "success":      "#286983",
        "error":        "#b4637a",
        "warning":      "#ea9d34",
        "syntax_kw":    "#907aa9",
        "syntax_fn":    "#56949f",
        "syntax_str":   "#286983",
        "syntax_num":   "#ea9d34",
        "syntax_cmt":   "#9893a5",
        "syntax_type":  "#d7827e",
    },
    "tokyonight": {
        "bg":           "#1a1b26",
        "bg_panel":     "#16161e",
        "bg_element":   "#1f2335",
        "border":       "#292e42",
        "border_active":"#3d59a1",
        "text":         "#c0caf5",
        "text_muted":   "#565f89",
        "primary":      "#7aa2f7",
        "secondary":    "#bb9af7",
        "accent":       "#7dcfff",
        "success":      "#9ece6a",
        "error":        "#f7768e",
        "warning":      "#e0af68",
        "syntax_kw":    "#bb9af7",
        "syntax_fn":    "#7aa2f7",
        "syntax_str":   "#9ece6a",
        "syntax_num":   "#ff9e64",
        "syntax_cmt":   "#565f89",
        "syntax_type":  "#7dcfff",
    },
    "vantablack": {
        "bg":           "#000000",
        "bg_panel":     "#404040",
        "bg_element":   "#5c5c5c",
        "border":       "#404040",
        "border_active":"#8d8d8d",
        "text":         "#ffffff",
        "text_muted":   "#5c5c5c",
        "primary":      "#8d8d8d",
        "secondary":    "#8d8d8d",
        "accent":       "#9b9b9b",
        "success":      "#b6b6b6",
        "error":        "#a4a4a4",
        "warning":      "#cecece",
        "syntax_kw":    "#9b9b9b",
        "syntax_fn":    "#8d8d8d",
        "syntax_str":   "#b6b6b6",
        "syntax_num":   "#cecece",
        "syntax_cmt":   "#5c5c5c",
        "syntax_type":  "#b0b0b0",
    },
    "white": {
        "bg":           "#ffffff",
        "bg_panel":     "#c0c0c0",
        "bg_element":   "#c0c0c0",
        "border":       "#c0c0c0",
        "border_active":"#6e6e6e",
        "text":         "#000000",
        "text_muted":   "#c0c0c0",
        "primary":      "#6e6e6e",
        "secondary":    "#1a1a1a",
        "accent":       "#2e2e2e",
        "success":      "#3a3a3a",
        "error":        "#2a2a2a",
        "warning":      "#4a4a4a",
        "syntax_kw":    "#2e2e2e",
        "syntax_fn":    "#1a1a1a",
        "syntax_str":   "#3a3a3a",
        "syntax_num":   "#4a4a4a",
        "syntax_cmt":   "#c0c0c0",
        "syntax_type":  "#3e3e3e",
    },
}

THEME_DESCRIPTIONS = {
    "system":               "Auto-detect system theme colors",
    "ayu":                  "Orange & teal on deep dark",
    "catppuccin":           "Soft pastel dark",
    "catppuccin-latte":     "Soft pastel light variant",
    "catppuccin-macchiato": "Darker catppuccin variant",
    "ethereal":             "Deep blue-purple with peach accents",
    "everforest":           "Warm green forest tones",
    "flexoki-light":        "Warm paper-toned light theme",
    "gruvbox":              "Retro warm brown & yellow",
    "hackerman":            "Neon green/cyan on deep dark",
    "kanagawa":             "Japanese ink-inspired blues",
    "lumon":                "Cool blue corporate theme",
    "matrix":               "Hacker green on black",
    "matte-black":          "Dark matte with amber accent",
    "miasma":               "Earthy olive and desert tones",
    "nord":                 "Arctic cold blue-grey",
    "one-dark":             "Atom One Dark",
    "opencode":             "OpenCode's default dark theme",
    "osaka-jade":           "Deep green and jade palette",
    "retro-82":             "Retro orange/teal on deep navy",
    "ristretto":            "Warm dusty rose palette",
    "rose-pine":            "Rosé Pine Dawn light theme",
    "tokyonight":           "Deep blue/purple nights",
    "vantablack":           "True black with monochrome grays",
    "white":                "Pure white with reverse grayscale",
}
